- name: Configure splunk peernode linux tunables
  hosts: peernode
  user: root

  tasks:
    - name: disable THP on boot via grub
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash transparent_hugepage=never"'
      notify: update grub

    - name: set splunk ulimit fd
      blockinfile:
        path: /etc/security/limits.d/splunk.conf
        create: yes
        block: |
          splunk        hard    nofile    65535
          splunk        soft    nofile    65535

    - name: tell PAM to read limits
      lineinfile:
        path: /etc/pam.d/common-session
        insertbefore: '# end of pam-auth-update config'
        line: session required        pam_limits.so

    - name: tell PAM to read limits non-interactive
      lineinfile:
        path: /etc/pam.d/common-session-noninteractive
        insertbefore: '# end of pam-auth-update config'
        line: session required        pam_limits.so
  handlers:
    - name: update grub
      shell: /usr/sbin/update-grub
